-- AlterTable
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "invoiceNextSeq" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "invoiceNumberPad" INTEGER NOT NULL DEFAULT 4;
