-- AlterTable
ALTER TABLE "settings" ADD COLUMN "sofPrefix" TEXT NOT NULL DEFAULT '';
ALTER TABLE "settings" ADD COLUMN "sofNextSeq" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "settings" ADD COLUMN "sofNumberPad" INTEGER NOT NULL DEFAULT 1;
